/* tslint:disable */
/* eslint-disable */
/**
 * ServicioConsumible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface EmailResponse {
    'done'?: boolean;
    'errorMessage'?: string | null;
}
export interface ProblemDetails {
    [key: string]: any;

    'type'?: string | null;
    'title'?: string | null;
    'status'?: number | null;
    'detail'?: string | null;
    'instance'?: string | null;
}
export interface Solicitud {
    'cantidadesIniciales'?: Array<number> | null;
    'nombreEntidades'?: Array<string> | null;
}

/**
 * EmailApi - axios parameter creator
 */
export const EmailApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [emailAddress] 
         * @param {string} [message] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        emailPost: async (emailAddress?: string, message?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (emailAddress !== undefined) {
                localVarQueryParameter['emailAddress'] = emailAddress;
            }

            if (message !== undefined) {
                localVarQueryParameter['message'] = message;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmailApi - functional programming interface
 */
export const EmailApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmailApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [emailAddress] 
         * @param {string} [message] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async emailPost(emailAddress?: string, message?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.emailPost(emailAddress, message, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmailApi.emailPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EmailApi - factory interface
 */
export const EmailApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmailApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [emailAddress] 
         * @param {string} [message] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        emailPost(emailAddress?: string, message?: string, options?: RawAxiosRequestConfig): AxiosPromise<EmailResponse> {
            return localVarFp.emailPost(emailAddress, message, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EmailApi - object-oriented interface
 */
export class EmailApi extends BaseAPI {
    /**
     * 
     * @param {string} [emailAddress] 
     * @param {string} [message] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public emailPost(emailAddress?: string, message?: string, options?: RawAxiosRequestConfig) {
        return EmailApiFp(this.configuration).emailPost(emailAddress, message, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ResultadosApi - axios parameter creator
 */
export const ResultadosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [nombreUsuario] 
         * @param {number} [tok] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resultadosPost: async (nombreUsuario?: string, tok?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Resultados`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (nombreUsuario !== undefined) {
                localVarQueryParameter['nombreUsuario'] = nombreUsuario;
            }

            if (tok !== undefined) {
                localVarQueryParameter['tok'] = tok;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ResultadosApi - functional programming interface
 */
export const ResultadosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ResultadosApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [nombreUsuario] 
         * @param {number} [tok] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resultadosPost(nombreUsuario?: string, tok?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resultadosPost(nombreUsuario, tok, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ResultadosApi.resultadosPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ResultadosApi - factory interface
 */
export const ResultadosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ResultadosApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [nombreUsuario] 
         * @param {number} [tok] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resultadosPost(nombreUsuario?: string, tok?: number, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.resultadosPost(nombreUsuario, tok, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ResultadosApi - object-oriented interface
 */
export class ResultadosApi extends BaseAPI {
    /**
     * 
     * @param {string} [nombreUsuario] 
     * @param {number} [tok] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public resultadosPost(nombreUsuario?: string, tok?: number, options?: RawAxiosRequestConfig) {
        return ResultadosApiFp(this.configuration).resultadosPost(nombreUsuario, tok, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SolicitudApi - axios parameter creator
 */
export const SolicitudApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [nombreUsuario] 
         * @param {number} [tok] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solicitudComprobarSolicitudGet: async (nombreUsuario?: string, tok?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Solicitud/ComprobarSolicitud`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (nombreUsuario !== undefined) {
                localVarQueryParameter['nombreUsuario'] = nombreUsuario;
            }

            if (tok !== undefined) {
                localVarQueryParameter['tok'] = tok;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [nombreUsuario] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solicitudGetSolicitudesUsuarioGet: async (nombreUsuario?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Solicitud/GetSolicitudesUsuario`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (nombreUsuario !== undefined) {
                localVarQueryParameter['nombreUsuario'] = nombreUsuario;
            }

            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [nombreUsuario] 
         * @param {Solicitud} [solicitud] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solicitudSolicitarPost: async (nombreUsuario?: string, solicitud?: Solicitud, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Solicitud/Solicitar`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (nombreUsuario !== undefined) {
                localVarQueryParameter['nombreUsuario'] = nombreUsuario;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/plain,application/json,text/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(solicitud, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SolicitudApi - functional programming interface
 */
export const SolicitudApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SolicitudApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [nombreUsuario] 
         * @param {number} [tok] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async solicitudComprobarSolicitudGet(nombreUsuario?: string, tok?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<number>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.solicitudComprobarSolicitudGet(nombreUsuario, tok, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SolicitudApi.solicitudComprobarSolicitudGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [nombreUsuario] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async solicitudGetSolicitudesUsuarioGet(nombreUsuario?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<number>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.solicitudGetSolicitudesUsuarioGet(nombreUsuario, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SolicitudApi.solicitudGetSolicitudesUsuarioGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [nombreUsuario] 
         * @param {Solicitud} [solicitud] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async solicitudSolicitarPost(nombreUsuario?: string, solicitud?: Solicitud, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.solicitudSolicitarPost(nombreUsuario, solicitud, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SolicitudApi.solicitudSolicitarPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SolicitudApi - factory interface
 */
export const SolicitudApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SolicitudApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [nombreUsuario] 
         * @param {number} [tok] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solicitudComprobarSolicitudGet(nombreUsuario?: string, tok?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<number>> {
            return localVarFp.solicitudComprobarSolicitudGet(nombreUsuario, tok, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [nombreUsuario] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solicitudGetSolicitudesUsuarioGet(nombreUsuario?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<number>> {
            return localVarFp.solicitudGetSolicitudesUsuarioGet(nombreUsuario, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [nombreUsuario] 
         * @param {Solicitud} [solicitud] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        solicitudSolicitarPost(nombreUsuario?: string, solicitud?: Solicitud, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.solicitudSolicitarPost(nombreUsuario, solicitud, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SolicitudApi - object-oriented interface
 */
export class SolicitudApi extends BaseAPI {
    /**
     * 
     * @param {string} [nombreUsuario] 
     * @param {number} [tok] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public solicitudComprobarSolicitudGet(nombreUsuario?: string, tok?: number, options?: RawAxiosRequestConfig) {
        return SolicitudApiFp(this.configuration).solicitudComprobarSolicitudGet(nombreUsuario, tok, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [nombreUsuario] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public solicitudGetSolicitudesUsuarioGet(nombreUsuario?: string, options?: RawAxiosRequestConfig) {
        return SolicitudApiFp(this.configuration).solicitudGetSolicitudesUsuarioGet(nombreUsuario, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [nombreUsuario] 
     * @param {Solicitud} [solicitud] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public solicitudSolicitarPost(nombreUsuario?: string, solicitud?: Solicitud, options?: RawAxiosRequestConfig) {
        return SolicitudApiFp(this.configuration).solicitudSolicitarPost(nombreUsuario, solicitud, options).then((request) => request(this.axios, this.basePath));
    }
}



